export default {
  // direct paths to folio apps to use in cy.visit() into initial steps of our scenarios
  // TODO: add separated scenarios related with SettingsMenu implementation
  acquisitionUnitsPath: 'settings/acquisition-units',
  agreementsPath: 'settings/erm',
  calendarPath: 'settings/calendar',
  // Circulation
  circulationRulesPath: 'settings/circulation/rules',
  circulationOtherSettingsPath: 'settings/circulation/checkout',
  circulationStaffSlipsPath: 'settings/circulation/staffslips',
  circulationFixedDueDateSchedulesPath: 'settings/circulation/fixed-due-date-schedules',
  circulationLoanHistoryPath: 'settings/circulation/loan-history',
  circulationLoanPoliciesPath: 'settings/circulation/loan-policies',
  circulationoVerdueFinePoliciesPath: 'settings/circulation/fine-policies',
  circulationLostItemFeePolicyPath: 'settings/circulation/lost-item-fee-policy',
  circulationPatronNoticePoliciesPath: 'settings/circulation/notice-policies',
  circulationPatronNoticeTemplatesPath: 'settings/circulation/patron-notices',
  circulationRequestCancellationReasonsPath: 'settings/circulation/cancellation-reasons',
  circulationRequestPoliciesPath: 'settings/circulation/request-policies',
  circulationTitleLevelRequestsPath: 'settings/circulation/title-level-requests',
  coursesPath: 'settings/cr',
  dashboardPath: 'settings/dashboard',
  dataExportPath: 'settings/data-export',
  dataImportPath: 'settings/data-import',
  developerPath: 'settings/developer',
  eHoldingsPath: 'settings/eholdings',
  ermComparisonsPath: 'settings/comparisons-erm',
  innReachPath: 'settings/innreach',
  inventoryPath: 'settings/inventory',
  // Invoice
  invoiceApprovalsPath: 'settings/invoice/approvals',
  invoiceAdjustmentsPath: 'settings/invoice/adjustments',
  invoiceBatchGroupsPath: 'settings/invoice/batch-groups',
  invoiceBGConfigPath: 'settings/invoice/batch-group-configuration',
  invoiceVoucherPath: 'settings/invoice/voucher-number',

  ldpPath: 'settings/ldp',
  licensesPath: 'settings/licenses',
  localKbAdminPath: 'settings/local-kb-admin',
  myProfilePath: 'settings/myprofile',
  notesPath: 'settings/notes',
  oaiPmhPath: 'settings/oai-pmh',
  openAccessPath: 'settings/oa',
  ordersPath: 'settings/orders',
  organizationsPath: 'settings/organizations',
  remoteStoragePath: 'settings/remote-storage',
  tagsPath: 'settings/tags',
  tenantPath: 'settings/tenant-settings',
  // Users
  usersOwnersPath: 'settings/users/owners',
};
