import { APPLICATION_NAMES, CAPABILITY_ACTIONS, CAPABILITY_TYPES } from '../../support/constants';
import Permissions from '../../support/dictionary/permissions';
import Organizations from '../../support/fragments/organizations/organizations';
import TopMenuNavigation from '../../support/fragments/topMenuNavigation';
import Users from '../../support/fragments/users/users';
import getRandomPostfix from '../../support/utils/stringTools';

describe('Organizations', () => {
  let user;
  const organization = {
    name: `autotest_org_${getRandomPostfix()}`,
    status: 'Active',
    code: `test_code_${getRandomPostfix()}`,
    isVendor: true,
  };
  const bankingInformation = {
    bankName: `AutoBank_${getRandomPostfix()}`,
    bankAccountNumber: '123456789012',
    transitNumber: '987654321',
    notes: 'Created from Automated test',
  };
  const testData = {
    capabSetsToAssign: [
      {
        table: CAPABILITY_TYPES.DATA,
        resource: 'UI-Organizations',
        action: CAPABILITY_ACTIONS.VIEW,
      },
      {
        table: CAPABILITY_TYPES.DATA,
        resource: 'UI-Organizations Banking-Information',
        action: CAPABILITY_ACTIONS.VIEW,
      },
    ],
    newCapabToAssign: {
      table: CAPABILITY_TYPES.DATA,
      resource: 'UI-Organizations',
      action: CAPABILITY_ACTIONS.EDIT,
    },
    role: {
      name: '',
      description: 'Autogenerated by Cypress',
      id: '',
    },
    capabSetIds: [],
  };

  before('Create test data', () => {
    cy.getAdminToken();
    Organizations.createOrganizationViaApi(organization).then((response) => {
      organization.id = response;
      bankingInformation.organizationId = response;
      Organizations.createBankingInformationViaApi(bankingInformation);
    });
    cy.createTempUser([
      Permissions.uiOrganizationsView.gui,
      Permissions.uiOrganizationsViewBankingInformation.gui,
    ])
      .then((userProperties) => {
        user = userProperties;

        testData.role.name = user.username;
        return cy.createAuthorizationRoleApi(testData.role.name, testData.role.description);
      })
      .then((role) => {
        testData.role.id = role.id;
        const promises = testData.capabSetsToAssign.map((set) => {
          return cy
            .getCapabilitySetIdViaApi({ ...set, type: set.table })
            .then((id) => testData.capabSetIds.push(id));
        });
        return Cypress.Promise.all(promises);
      })
      .then(() => {
        return cy.addCapabilitySetsToNewRoleApi(testData.role.id, testData.capabSetIds);
      })
      .then(() => {
        return cy.updateRolesForUserApi(user.userId, [testData.role.id]);
      });
  });

  after('Delete test data', () => {
    cy.getAdminToken();
    Users.deleteViaApi(user.userId);
    cy.deleteAuthorizationRoleApi(testData.role.id);
    Organizations.deleteOrganizationViaApi(organization.id);
  });

  it(
    'C423503 A user can only view banking information with "Organizations: View banking information" permission (thunderjet)',
    { tags: ['criticalPath', 'thunderjet', 'C423503'] },
    () => {
      cy.login(user.username, user.password);
      TopMenuNavigation.navigateToApp(APPLICATION_NAMES.ORGANIZATIONS);
      Organizations.waitLoading();
      Organizations.searchByParameters('Name', organization.name);
      Organizations.selectOrganization(organization.name);
      Organizations.verifyBankingInformationAccordionIsPresent();
      Organizations.checkBankInformationExist(bankingInformation.bankName);
      Organizations.checkBankInformationExist(bankingInformation.bankAccountNumber);
      Organizations.checkAvailableActionsInTheActionsField();

      // update user capabilities to edit organization
      cy.getAdminToken();
      cy.getCapabilitySetIdViaApi({
        ...testData.newCapabToAssign,
        type: testData.newCapabToAssign.table,
      })
        .then((newSetId) => {
          return cy.addCapabilitySetsToNewRoleApi(testData.role.id, [newSetId]);
        })
        .then(() => {
          cy.login(user.username, user.password);
          TopMenuNavigation.navigateToApp(APPLICATION_NAMES.ORGANIZATIONS);
          Organizations.waitLoading();
          Organizations.searchByParameters('Name', organization.name);
          Organizations.selectOrganization(organization.name);
          Organizations.verifyBankingInformationAccordionIsPresent();
          Organizations.editOrganization();
          Organizations.verifyBankingInformationAccordionIsAbsent();
        });
    },
  );
});
