import { APPLICATION_NAMES, CAPABILITY_ACTIONS, CAPABILITY_TYPES } from '../../support/constants';
import Permissions from '../../support/dictionary/permissions';
import Organizations from '../../support/fragments/organizations/organizations';
import SettingsOrganizations from '../../support/fragments/settings/organizations/settingsOrganizations';
import TopMenu from '../../support/fragments/topMenu';
import TopMenuNavigation from '../../support/fragments/topMenuNavigation';
import Users from '../../support/fragments/users/users';
import getRandomPostfix from '../../support/utils/stringTools';

describe('Organizations', () => {
  let userA;
  const organization = {
    name: `autotest_org_${getRandomPostfix()}`,
    status: 'Active',
    code: `autotest_code_${getRandomPostfix()}`,
    isVendor: true,
    erpCode: `ERP-${getRandomPostfix()}`,
  };
  const bankingInformation = {
    bankName: `Test Bank ${Date.now()}`,
    bankAccountNumber: '1234567890',
    transitNumber: '987654321',
    notes: 'Test banking information',
  };
  const capabSetsToAssign = {
    table: CAPABILITY_TYPES.DATA,
    resource: 'UI-Organizations',
    action: CAPABILITY_ACTIONS.CREATE,
  };

  const newCapabToAssign = {
    table: CAPABILITY_TYPES.DATA,
    resource: 'UI-Organizations',
    action: CAPABILITY_ACTIONS.DELETE,
  };
  const role = { id: '', name: '', description: 'Autogenerated by Cypress' };

  before(() => {
    cy.getAdminToken();
    SettingsOrganizations.getBankingInformationStatusViaApi().then((response) => {
      if (response.settings[0].value === 'false') {
        response.settings[0].value = true;
        SettingsOrganizations.enableBankingInformationViaApi(response);
      }
    });
    Organizations.createOrganizationViaApi(organization).then((orgId) => {
      organization.id = orgId;
      bankingInformation.organizationId = orgId;
      Organizations.createBankingInformationViaApi(bankingInformation);
    });

    cy.createTempUser([Permissions.uiOrganizationsViewEditCreate.gui])
      .then((u) => {
        userA = u;
        role.name = userA.username;
        return cy.createAuthorizationRoleApi(role.name, role.description);
      })
      .then((createdRole) => {
        role.id = createdRole.id;
        return cy
          .getCapabilitySetIdViaApi({ ...capabSetsToAssign, type: capabSetsToAssign.table })
          .then((setId) => cy.addCapabilitySetsToNewRoleApi(role.id, [setId]));
      })
      .then(() => {
        return cy.updateRolesForUserApi(userA.userId, [role.id]);
      });
  });

  after(() => {
    cy.getAdminToken();
    Organizations.deleteOrganizationViaApi(organization.id);
    cy.deleteAuthorizationRoleApi(role.id);
    Users.deleteViaApi(userA.userId);
  });

  it(
    'C423516 User cannot view banking information without banking information permission (thunderjet)',
    { tags: ['criticalPath', 'thunderjet', 'C423516'] },
    () => {
      cy.login(userA.username, userA.password);
      TopMenuNavigation.navigateToApp(APPLICATION_NAMES.ORGANIZATIONS);
      Organizations.waitLoading();
      Organizations.searchByParameters('Name', organization.name);
      Organizations.checkSearchResults(organization);
      Organizations.selectOrganization(organization.name);
      Organizations.editOrganization();
      Organizations.verifyBankingInformationAccordionIsAbsent();

      cy.getAdminToken();
      cy.getCapabilitySetIdViaApi({ ...capabSetsToAssign, type: capabSetsToAssign.table })
        .then((oldSetId) => {
          return cy
            .getCapabilitySetIdViaApi({ ...newCapabToAssign, type: newCapabToAssign.table })
            .then((newSetId) => ({ oldSetId, newSetId }));
        })
        .then(({ oldSetId, newSetId }) => {
          return cy.deleteCapabilitySetsFromRoleApi(role.id).then(() => ({ oldSetId, newSetId }));
        })
        .then(({ oldSetId, newSetId }) => {
          return cy
            .addCapabilitySetsToNewRoleApi(role.id, [newSetId])
            .then(() => ({ oldSetId, newSetId }));
        });

      cy.login(userA.username, userA.password, {
        path: TopMenu.organizationsPath,
        waiter: Organizations.waitLoading,
      });
      Organizations.searchByParameters('Name', organization.name);
      Organizations.checkSearchResults(organization);
      Organizations.selectOrganization(organization.name);
      Organizations.editOrganization();
      Organizations.verifyBankingInformationAccordionIsAbsent();
      Organizations.cancelOrganization();
      Organizations.waitLoading();
      cy.wait(3000);
      Organizations.verifyBankingInformationAccordionIsAbsent();
    },
  );
});
