export const FEE_FINE_ACCOUNTS_WITH_USERS_FIELDS = {
  FEE_FINE_ACCOUNTS: {
    AMOUNT: 'Fee/Fine accounts — Amount',
    BARCODE: 'Fee/Fine accounts — Barcode',
    CREATED_AT: 'Fee/Fine accounts — Created at',
    DUE_DATE: 'Fee/Fine accounts — Due date',
    FEE_FINE_OWNER: 'Fee/Fine accounts — Fee/fine owner',
    FEE_FINE_TYPE: 'Fee/Fine accounts — Fee/fine type',
    LOCATION: 'Fee/Fine accounts — Location',
    MATERIAL_TYPE: 'Fee/Fine accounts — Material type',
    PAYMENT_STATUS_NAME: 'Fee/Fine accounts — Payment status name',
    REMAINING: 'Fee/Fine accounts — Remaining',
    RETURNED_DATE: 'Fee/Fine accounts — Returned date',
    STATUS_NAME: 'Fee/Fine accounts — Status name',
    UPDATED_AT: 'Fee/Fine accounts — Updated at',
    USER_UUID: 'Fee/Fine accounts — User UUID',
    UUID: 'Fee/Fine accounts — UUID',
  },
  USER: {
    ACTIVE: 'User — Active',
    ADDRESS_CITY: 'User — Address — City',
    ADDRESS_COUNTRY: 'User — Address — Country',
    ADDRESS_LINE_1: 'User — Address — Line 1',
    ADDRESS_LINE_2: 'User — Address — Line 2',
    ADDRESS_POSTAL_CODE: 'User — Address — Postal code',
    ADDRESS_PRIMARY_ADDRESS: 'User — Address — Primary address',
    ADDRESS_REGION: 'User — Address — Region',
    ADDRESS_TYPE: 'User — Address — Type',
    BARCODE: 'User — Barcode',
    CREATED_BY_USER_UUID: 'User — Created by user UUID',
    DATE_OF_BIRTH: 'User — Date of birth',
    DEPARTMENT_NAMES: 'User — Department names',
    EMAIL: 'User — Email',
    ENROLLMENT_DATE: 'User — Enrollment date',
    EXPIRATION_DATE: 'User — Expiration date',
    EXTERNAL_SYSTEM_ID: 'User — External system ID',
    FIRST_NAME: 'User — First name',
    LAST_NAME: 'User — Last name',
    LAST_NAME_FIRST_NAME: 'User — Last name, first name',
    MIDDLE_NAME: 'User — Middle name',
    MOBILE_PHONE: 'User — Mobile phone',
    PHONE: 'User — Phone',
    PREFERRED_CONTACT_TYPE: 'User — Preferred contact type',
    PREFERRED_FIRST_NAME: 'User — Preferred first name',
    PRONOUNS: 'User — Pronouns',
    TAGS: 'User — Tags',
    TYPE: 'User — Type',
    UPDATED_BY_USER_UUID: 'User — Updated by user UUID',
    USER_CREATED_DATE: 'User — User created date',
    USER_UPDATED_DATE: 'User — User updated date',
    USER_UUID: 'User — User UUID',
    USERNAME: 'User — Username',
  },
  PATRON_GROUP: {
    NAME: 'User — Patron group — Name',
  },
};
