export const LOST_ITEMS_REQUIRING_ACTUAL_COST_FIELDS = {
  ACTUAL_COST: {
    ADDITIONAL_INFO_FOR_PATRON: 'Actual cost — Additional info for patron',
    ADDITIONAL_INFO_FOR_STAFF: 'Actual cost — Additional info for staff',
    CREATED_AT: 'Actual cost — Created at',
    EXPIRATION_DATE: 'Actual cost — Expiration date',
    FEE_FINE_ACCOUNT_UUID: 'Actual cost — Fee fine account UUID',
    FEE_FINE_BILLED_AMOUNT: 'Actual cost — Fee fine billed amount',
    FEE_FINE_OWNER: 'Actual cost — Fee fine owner',
    FEE_FINE_TYPE: 'Actual cost — Fee fine type',
    INSTANCE_CONTRIBUTORS_NAME: 'Actual cost — Instance contributors name',
    INSTANCE_IDENTIFIERS_TYPE_NAME: 'Actual cost — Instance identifiers type name',
    INSTANCE_IDENTIFIERS_TYPE_UUID: 'Actual cost — Instance identifiers type UUID',
    INSTANCE_IDENTIFIERS_VALUE: 'Actual cost — Instance identifiers value',
    INSTANCE_TITLE: 'Actual cost — Instance title',
    INSTANCE_UUID: 'Actual cost — Instance UUID',
    ITEM_BARCODE: 'Actual cost — Item barcode',
    ITEM_EFFECTIVE_LOCATION: 'Actual cost — Item effective location',
    ITEM_LOAN_TYPE: 'Actual cost — Item loan type',
    ITEM_MATERIAL_TYPE: 'Actual cost — Item material type',
    ITEM_PERMANENT_LOCATION: 'Actual cost — Item permanent location',
    ITEM_UUID: 'Actual cost — Item UUID',
    LOAN_UUID: 'Actual cost — Loan UUID',
    LOSS_DATE: 'Actual cost — Loss date',
    LOSS_TYPE: 'Actual cost — Loss type',
    STATUS: 'Actual cost — Status',
    UPDATED_AT: 'Actual cost — Updated at',
    USER_BARCODE: 'Actual cost — User barcode',
    USER_FIRST_NAME: 'Actual cost — User first name',
    USER_LAST_NAME: 'Actual cost — User last name',
    USER_MIDDLE_NAME: 'Actual cost — User middle name',
    USER_PATRON_GROUP: 'Actual cost — User patron group',
    USER_UUID: 'Actual cost — User UUID',
    UUID: 'Actual cost — UUID',
  },
  ACTUAL_COST_CREATED_BY: {
    EMAIL: 'Actual cost — Created by — Email',
    LAST_NAME_FIRST_NAME: 'Actual cost — Created by — Last name, first name',
    USERNAME: 'Actual cost — Created by — Username',
  },
  ACTUAL_COST_UPDATED_BY: {
    EMAIL: 'Actual cost — Updated by — Email',
    LAST_NAME_FIRST_NAME: 'Actual cost — Updated by — Last name, first name',
    USERNAME: 'Actual cost — Updated by — Username',
  },
  USER: {
    ACTIVE: 'User — Active',
    BARCODE: 'User — Barcode',
    DEPARTMENT_NAMES: 'User — Department names',
    DEPARTMENT_UUIDS: 'User — Department UUIDs',
    EMAIL: 'User — Email',
    EXPIRATION_DATE: 'User — Expiration date',
    LAST_NAME_FIRST_NAME: 'User — Last name, first name',
    PRONOUNS: 'User — Pronouns',
    TAGS: 'User — Tags',
    TYPE: 'User — Type',
    USER_UUID: 'User — User UUID',
  },
};
