export const ORGANIZATIONS_FIELDS = {
  ORGANIZATION: {
    TAGS: 'Organization — Tags',
    UPDATED_AT: 'Organization — Updated at',
    DESCRIPTION: 'Organization — Description',
    ADDRESSES: {
      ADDRESS_LINE_1: 'Organization — Addresses — Address line 1',
      ADDRESS_LINE_2: 'Organization — Addresses — Address line 2',
      CITY: 'Organization — Addresses — City',
      STATE_REGION: 'Organization — Addresses — State/region',
      ZIP_CODE: 'Organization — Addresses — Zip code',
      COUNTRY: 'Organization — Addresses — Country',
      CATEGORIES: 'Organization — Addresses — Categories',
    },
    ADDRESSES_COLUMN: 'Organization — Addresses',
    URLS: {
      URL: 'Organization — URLs — URL',
      DESCRIPTION: 'Organization — URLs — Description',
      CATEGORIES: 'Organization — URLs — Categories',
      NOTES: 'Organization — URLs — Notes',
    },
    URLS_COLUMN: 'Organization — URLs',
    ACCOUNTS: {
      NAME: 'Organization — Accounts — Name',
      ACCOUNT_NUMBER: 'Organization — Accounts — Account number',
      DESCRIPTION: 'Organization — Accounts — Description',
      ACCOUNTING_CODE: 'Organization — Accounts — Accounting code',
      PAYMENT_METHOD: 'Organization — Accounts — Payment method',
      STATUS: 'Organization — Accounts — Status',
      CONTACT_INFO: 'Organization — Accounts — Contact info',
      LIBRARY_CODE: 'Organization — Accounts — Library code',
      LIBRARY_EDI_CODE: 'Organization — Accounts — Library EDI code',
      NOTES: 'Organization — Accounts — Notes',
      ACQUISITIONS_UNIT_NAMES: 'Organization — Accounts — Acquisition unit names',
    },
    ACCOUNTS_COLUMN: 'Organization — Accounts',
    EMAILS: {
      EMAIL_ADDRESS: 'Organization — Emails — Email',
      DESCRIPTION: 'Organization — Emails — Description',
      CATEGORIES: 'Organization — Emails — Categories',
    },
    EMAILS_COLUMN: 'Organization — Emails',
    PHONE_NUMBERS: {
      PHONE_NUMBER: 'Organization — Phone numbers — Phone number',
      TYPE: 'Organization — Phone numbers — Type',
      CATEGORIES: 'Organization — Phone numbers — Categories',
    },
    PHONE_NUMBERS_COLUMN: 'Organization — Phone numbers',
  },
};
