export const PURCHASE_ORDER_LINES_FIELDS = {
  POL: {
    TAGS: 'POL — Tags',
    CREATED_AT: 'POL — Created at',
    PO_LINE_NUMBER: 'POL — PO line number',
    TITLE_OR_PACKAGE: 'POL — Title or package',
    UPDATED_AT: 'POL — Updated at',
    UUID: 'POL — UUID',
    EXCHANGE_RATE: 'POL exchange rate',
    ACQUISITION_METHOD: 'POL — Acquisition method',
    AGREEMENT_UUID: 'POL — Agreement UUID',
    COST_CURRENCY: 'POL — Cost currency',
    COST_EXCHANGE_RATE: 'POL — Cost exchange rate',
    COST_PO_LINE_ESTIMATED_PRICE: 'POL — Cost PO line estimated price',
    DESCRIPTION: 'POL — Description',
    DETAILS_RECEIVING_NOTE: 'POL — Details receiving note',
    DONOR: 'POL — Donor',
    E_RESOURCE_CREATE_INVENTORY: 'POL — E-resource create inventory',
    E_RESOURCE_EXPECTED_ACTIVATION: 'POL — E-resource expected activation',
    E_RESOURCE_IS_ACTIVATED: 'POL — E-resource is activated',
    E_RESOURCE_IS_TRIAL: 'POL — E-resource is trial',
    E_RESOURCE_RESOURCE_URL: 'POL — E-resource resource url',
    FUND_DISTRIBUTION: 'POL — Fund distribution',
    IS_RUSH: 'POL — Is rush',
    LOCATIONS: 'POL — Locations',
    MEMBERSHIP: 'POL — Membership',
    MULTI_YEAR_PREPAYMENT: 'POL — Multi-year prepayment',
    ORDER_FORMAT: 'POL — Order format',
    PAYMENT_STATUS: 'POL — Payment status',
    PAYMENT_TERMS: 'POL — Payment terms',
    PHYSICAL_EXPECTED_RECEIPT_DATE: 'POL — Physical expected receipt date',
    PREPAYMENT_TERM: 'POL — Prepayment term',
    PUBLICATION_DATE: 'POL — Publication date',
    PUBLISHER: 'POL — Publisher',
    RECEIPT_DATE: 'POL — Receipt date',
    RECEIPT_STATUS: 'POL — Receipt status',
    SELECTOR: 'POL — Selector',
    SOURCE: 'POL — Source',
    STARTING_FISCAL_YEAR: 'POL — Starting fiscal year',
  },
  POL_CREATED_BY: {
    EMAIL: 'POL created by — Email',
    LAST_NAME_FIRST_NAME: 'POL created by — Last name, first name',
    USERNAME: 'POL created by — Username',
  },
  POL_UPDATED_BY: {
    EMAIL: 'POL updated by — Email',
    LAST_NAME_FIRST_NAME: 'POL updated by — Last name, first name',
    USERNAME: 'POL updated by — Username',
  },
  EXCHANGE_RATE: {
    CURRENCY: 'Exchange rate — Currency',
    RATE: 'Exchange rate — Rate',
  },
  PO: {
    TAGS: 'PO — Tags',
    APPROVED: 'PO — Approved',
    DATE_ORDERED: 'PO — Date ordered',
    ORDER_TYPE: 'PO — Order type',
    PO_NUMBER: 'PO — PO number',
    UPDATED_AT: 'PO — Updated at',
    WORKFLOW_STATUS: 'PO — Workflow status',
    ACQUISITION_UNIT_NAMES: 'PO — Acquisition unit names',
    ACQUISITION_UNIT_UUIDS: 'PO — Acquisition unit UUIDs',
    CLOSE_REASON: 'PO — Close reason',
    CREATED_AT: 'PO — Created at',
    EXTERNAL_ORDER_NUMBER: 'PO — External order number',
    RE_ENCUMBER: 'PO — Re-encumber',
    UUID: 'PO — UUID',
  },
  PO_ASSIGNED_TO_USER: {
    EMAIL: 'PO assigned to user — Email',
    LAST_NAME_FIRST_NAME: 'PO assigned to user — Last name, first name',
    USERNAME: 'PO assigned to user — Username',
  },
  PO_CREATED_BY: {
    EMAIL: 'PO created by — Email',
    LAST_NAME_FIRST_NAME: 'PO created by — Last name, first name',
    USERNAME: 'PO created by — Username',
  },
  PO_UPDATED_BY: {
    EMAIL: 'PO updated by — Email',
    LAST_NAME_FIRST_NAME: 'PO updated by — Last name, first name',
    USERNAME: 'PO updated by — Username',
  },
  VENDOR_ORG: {
    TAGS: 'Vendor org — Tags',
    CODE: 'Vendor org — Code',
    NAME: 'Vendor org — Name',
    STATUS: 'Vendor org — Status',
    EDI_VENDOR_CODE: 'Vendor org — EDI vendor code',
    EDI_VENDOR_TYPE: 'Vendor org — EDI vendor type',
    IS_DONOR: 'Vendor org — Is donor',
    IS_VENDOR: 'Vendor org — Is vendor',
    UUID: 'Vendor org — UUID',
  },
};
