export const RECEIVING_PIECES_FIELDS = {
  PIECES: {
    ACCESSION_NUMBER: 'Pieces — Accession number',
    BARCODE: 'Pieces — Barcode',
    BIND_ITEM_TENANT_ID: 'Pieces — Bind item tenant ID',
    CALL_NUMBER: 'Pieces — Call number',
    CHRONOLOGY: 'Pieces — Chronology',
    CLAIMING_INTERVAL: 'Pieces — Claiming interval',
    COMMENT: 'Pieces — Comment',
    COPY_NUMBER: 'Pieces — Copy number',
    CREATED_AT: 'Pieces — Created at',
    DISCOVERY_SUPPRESS: 'Pieces — Discovery suppress',
    DISPLAY_ON_HOLDING: 'Pieces — Display on holding',
    DISPLAY_SUMMARY: 'Pieces — Display summary',
    DISPLAY_TO_PUBLIC: 'Pieces — Display to public',
    ENUMERATION: 'Pieces — Enumeration',
    EXPECTED_RECEIPT_DATE: 'Pieces — Expected receipt date',
    EXTERNAL_NOTE: 'Pieces — External note',
    FORMAT: 'Pieces — Format',
    INTERNAL_NOTE: 'Pieces — Internal note',
    IS_BOUND: 'Pieces — Is bound',
    RECEIVED_DATE: 'Pieces — Received date',
    RECEIVING_STATUS: 'Pieces — Receiving status',
    RECEIVING_TENANT_ID: 'Pieces — Receiving tenant ID',
    SEQUENCE_NUMBER: 'Pieces — Sequence number',
    STATUS_UPDATED_DATE: 'Pieces — Status updated date',
    SUPPLEMENT: 'Pieces — Supplement',
    UPDATED_AT: 'Pieces — Updated at',
    UUID: 'Pieces — UUID',
  },
  ITEM: {
    ACCESSION_NUMBER: 'Item — Accession number',
    ADMINISTRATIVE_NOTES: 'Item — Administrative notes',
    BARCODE: 'Item — Barcode',
    CHECK_IN_NOTES_NOTE: 'Item — Check in notes — Note',
    CHECK_IN_NOTES_STAFF_ONLY: 'Item — Check in notes — Staff only',
    CHECK_OUT_NOTES_NOTE: 'Item — Check out notes — Note',
    CHECK_OUT_NOTES_STAFF_ONLY: 'Item — Check out notes — Staff only',
    CHRONOLOGY: 'Item — Chronology',
    COPY_NUMBER: 'Item — Copy number',
    CREATED_DATE: 'Item — Created date',
    DESCRIPTION_OF_PIECES: 'Item — Description of pieces',
    DISPLAY_SUMMARY: 'Item — Display summary',
    EFFECTIVE_CALL_NUMBER: 'Item — Effective call number',
    EFFECTIVE_SHELVING_ORDER: 'Item — Effective shelving order',
    ELECTRONIC_ACCESS_LINK_TEXT: 'Item — Electronic access — Link text',
    ELECTRONIC_ACCESS_MATERIAL_SPECIFIED: 'Item — Electronic access — Material specified',
    ELECTRONIC_ACCESS_URI: 'Item — Electronic access — URI',
    ELECTRONIC_ACCESS_URL_PUBLIC_NOTE: 'Item — Electronic access — URL public note',
    ELECTRONIC_ACCESS_URL_RELATIONSHIP: 'Item — Electronic access — URL relationship',
    ENUMERATION: 'Item — Enumeration',
    FORMER_IDENTIFIERS: 'Item — Former identifiers',
    ITEM_ADDITIONAL_CALL_NUMBERS_CALL_NUMBER: 'Item — Item additional call numbers — Call number',
    ITEM_ADDITIONAL_CALL_NUMBERS_PREFIX: 'Item — Item additional call numbers — Prefix',
    ITEM_ADDITIONAL_CALL_NUMBERS_SUFFIX: 'Item — Item additional call numbers — Suffix',
    ITEM_ADDITIONAL_CALL_NUMBERS_TYPE: 'Item — Item additional call numbers — Type',
    ITEM_CALL_NUMBER: 'Item — Item call number',
    ITEM_CALL_NUMBER_PREFIX: 'Item — Item call number prefix',
    ITEM_CALL_NUMBER_SUFFIX: 'Item — Item call number suffix',
    ITEM_HRID: 'Item — Item HRID',
    ITEM_UUID: 'Item — Item UUID',
    LAST_CHECK_IN_DATE_TIME: 'Item — Last check in date time',
    NOTES_NOTE: 'Item — Notes — Note',
    NOTES_NOTE_TYPE: 'Item — Notes — Note type',
    NOTES_STAFF_ONLY: 'Item — Notes — Staff only',
    NUMBER_OF_MISSING_PIECES: 'Item — Number of missing pieces',
    NUMBER_OF_PIECES: 'Item — Number of pieces',
    PURCHASE_ORDER_LINE_IDENTIFIER: 'Item — Purchase order line identifier',
    SORT_ORDER: 'Item — Sort order',
    STATISTICAL_CODES: 'Item — Statistical codes',
    STATUS: 'Item — Status',
    STATUS_DATE: 'Item — Status date',
    SUPPRESS_FROM_DISCOVERY: 'Item — Suppress from discovery',
    TAGS: 'Item — Tags',
    UPDATED_DATE: 'Item — Updated date',
    VERSION: 'Item — Version',
    VOLUME: 'Item — Volume',
    YEAR_CAPTION: 'Item — Year, caption',
  },
  LOCATION: {
    CODE: 'Location — Code',
    NAME: 'Location — Name',
  },
  POL: {
    ACQUISITION_METHOD: 'POL — Acquisition method',
    AGREEMENT_UUID: 'POL — Agreement UUID',
    COST_CURRENCY: 'POL — Cost currency',
    COST_EXCHANGE_RATE: 'POL — Cost exchange rate',
    COST_PO_LINE_ESTIMATED_PRICE: 'POL — Cost PO line estimated price',
    CREATED_AT: 'POL — Created at',
    DESCRIPTION: 'POL — Description',
    DETAILS_RECEIVING_NOTE: 'POL — Details receiving note',
    DONOR: 'POL — Donor',
    E_RESOURCE_CREATE_INVENTORY: 'POL — E-resource create inventory',
    E_RESOURCE_EXPECTED_ACTIVATION: 'POL — E-resource expected activation',
    E_RESOURCE_IS_ACTIVATED: 'POL — E-resource is activated',
    E_RESOURCE_IS_TRIAL: 'POL — E-resource is trial',
    E_RESOURCE_RESOURCE_URL: 'POL — E-resource resource url',
    FUND_DISTRIBUTION_CODE: 'POL — Fund distribution — Code',
    FUND_DISTRIBUTION_DISTRIBUTION_TYPE: 'POL — Fund distribution — Distribution type',
    FUND_DISTRIBUTION_ENCUMBRANCE_UUID: 'POL — Fund distribution — Encumbrance UUID',
    FUND_DISTRIBUTION_EXPENSE_CLASS: 'POL — Fund distribution — Expense class',
    FUND_DISTRIBUTION_FUND: 'POL — Fund distribution — Fund',
    IS_RUSH: 'POL — Is rush',
    LOCATIONS_CODE: 'POL — Locations — Code',
    LOCATIONS_NAME: 'POL — Locations — Name',
    MEMBERSHIP: 'POL — Membership',
    ORDER_FORMAT: 'POL — Order format',
    PAYMENT_STATUS: 'POL — Payment status',
    PHYSICAL_EXPECTED_RECEIPT_DATE: 'POL — Physical expected receipt date',
    PO_LINE_NUMBER: 'POL — PO line number',
    PUBLICATION_DATE: 'POL — Publication date',
    PUBLISHER: 'POL — Publisher',
    RECEIPT_DATE: 'POL — Receipt date',
    RECEIPT_STATUS: 'POL — Receipt status',
    SELECTOR: 'POL — Selector',
    SOURCE: 'POL — Source',
    TITLE_OR_PACKAGE: 'POL — Title or package',
    UPDATED_AT: 'POL — Updated at',
    UUID: 'POL — UUID',
  },
  TITLE: {
    CLAIMING_ACTIVE: 'Title — Claiming active',
    CLAIMING_INTERVAL: 'Title — Claiming interval',
    CONTRIBUTORS_NAME: 'Title — Contributors — Name',
    CREATED_AT: 'Title — Created at',
    EDITION: 'Title — Edition',
    EXPECTED_RECEIPT_DATE: 'Title — Expected receipt date',
    IS_ACKNOWLEDGED: 'Title — Is acknowledged',
    NEXT_SEQUENCE_NUMBER: 'Title — Next sequence number',
    PACKAGE_NAME: 'Title — Package name',
    PO_LINE_NUMBER: 'Title — PO line number',
    PRODUCT_IDENTIFIERS_PRODUCT_ID: 'Title — Product identifiers — Product ID',
    PRODUCT_IDENTIFIERS_PRODUCT_ID_TYPE: 'Title — Product identifiers — Product ID type',
    PRODUCT_IDENTIFIERS_QUALIFIER: 'Title — Product identifiers — Qualifier',
    PUBLISHED_DATE: 'Title — Published date',
    PUBLISHER: 'Title — Publisher',
    RECEIVING_NOTE: 'Title — Receiving note',
    SUBSCRIPTION_FROM: 'Title — Subscription from',
    SUBSCRIPTION_INTERVAL: 'Title — Subscription interval',
    SUBSCRIPTION_TO: 'Title — Subscription to',
    TITLE: 'Title — Title',
    UPDATED_AT: 'Title — Updated at',
    UUID: 'Title — UUID',
  },
  HOLDINGS: {
    ACQUISITION_METHOD: 'Holdings — Acquisition method',
    ACQUISITION_ORDER_FORMAT: 'Holdings — Acquisition order format',
    ACQUISITION_RECEIPT_STATUS: 'Holdings — Acquisition receipt status',
    ADMINISTRATIVE_NOTES: 'Holdings — Administrative notes',
    CALL_NUMBER: 'Holdings — Call number',
    CALL_NUMBER_PREFIX: 'Holdings — Call number prefix',
    CALL_NUMBER_SUFFIX: 'Holdings — Call number suffix',
    COPY_NUMBER: 'Holdings — Copy number',
    CREATED_DATE: 'Holdings — Created date',
    DIGITIZATION_POLICY: 'Holdings — Digitization policy',
    ELECTRONIC_ACCESS_LINK_TEXT: 'Holdings — Electronic access — Link text',
    ELECTRONIC_ACCESS_MATERIAL_SPECIFIED: 'Holdings — Electronic access — Material specified',
    ELECTRONIC_ACCESS_URI: 'Holdings — Electronic access — URI',
    ELECTRONIC_ACCESS_URL_PUBLIC_NOTE: 'Holdings — Electronic access — URL public note',
    ELECTRONIC_ACCESS_URL_RELATIONSHIP: 'Holdings — Electronic access — URL relationship',
    FORMER_IDENTIFIERS: 'Holdings — Former identifiers',
    HOLDINGS_ADDITIONAL_CALL_NUMBERS_CALL_NUMBER:
      'Holdings — Holdings additional call numbers — Call number',
    HOLDINGS_ADDITIONAL_CALL_NUMBERS_PREFIX: 'Holdings — Holdings additional call numbers — Prefix',
    HOLDINGS_ADDITIONAL_CALL_NUMBERS_SUFFIX: 'Holdings — Holdings additional call numbers — Suffix',
    HOLDINGS_ADDITIONAL_CALL_NUMBERS_TYPE: 'Holdings — Holdings additional call numbers — Type',
    HRID: 'Holdings — HRID',
    INSTANCE_UUID: 'Holdings — Instance UUID',
    NOTES_NOTE: 'Holdings — Notes — Note',
    NOTES_NOTE_TYPE: 'Holdings — Notes — Note type',
    NOTES_STAFF_ONLY: 'Holdings — Notes — Staff only',
    NUMBER_OF_ITEMS: 'Holdings — Number of items',
    RECEIVING_HISTORY_CHRONOLOGY: 'Holdings — Receiving history — Chronology',
    RECEIVING_HISTORY_ENUMERATION: 'Holdings — Receiving history — Enumeration',
    RECEIVING_HISTORY_PUBLIC_DISPLAY: 'Holdings — Receiving history — Public display',
    RECORD_VERSION: 'Holdings — Record version',
    RETENTION_POLICY: 'Holdings — Retention policy',
    SHELVING_TITLE: 'Holdings — Shelving title',
    STATEMENTS_STATEMENT: 'Holdings — Statements — Statement',
    STATEMENTS_STATEMENT_PUBLIC_NOTE: 'Holdings — Statements — Statement public note',
    STATEMENTS_STATEMENT_STAFF_NOTE: 'Holdings — Statements — Statement staff note',
    STATEMENTS_FOR_INDEXES_STATEMENT_FOR_INDEXES:
      'Holdings — Statements for indexes — Statement for indexes',
    STATEMENTS_FOR_INDEXES_STATEMENT_FOR_INDEXES_PUBLIC_NOTE:
      'Holdings — Statements for indexes — Statement for indexes public note',
    STATEMENTS_FOR_INDEXES_STATEMENT_FOR_INDEXES_STAFF_NOTE:
      'Holdings — Statements for indexes — Statement for indexes staff note',
    STATEMENTS_FOR_SUPPLEMENTS_STATEMENT_FOR_SUPPLEMENT:
      'Holdings — Statements for supplements — Statement for supplement',
    STATEMENTS_FOR_SUPPLEMENTS_STATEMENT_FOR_SUPPLEMENT_PUBLIC_NOTE:
      'Holdings — Statements for supplements — Statement for supplement public note',
    STATEMENTS_FOR_SUPPLEMENTS_STATEMENT_FOR_SUPPLEMENT_STAFF_NOTE:
      'Holdings — Statements for supplements — Statement for supplement staff note',
    STATISTICAL_CODES: 'Holdings — Statistical codes',
    STATISTICAL_CODE_UUIDS: 'Holdings — Statistical code UUIDs',
    SUPPRESS_FROM_DISCOVERY: 'Holdings — Suppress from discovery',
    TAGS: 'Holdings — Tags',
    UPDATED_DATE: 'Holdings — Updated date',
    UUID: 'Holdings — UUID',
  },
  PO: {
    ACQUISITION_UNIT_NAMES: 'PO — Acquisition unit names',
    APPROVED: 'PO — Approved',
    CLOSE_REASON: 'PO — Close reason',
    CREATED_AT: 'PO — Created at',
    DATE_ORDERED: 'PO — Date ordered',
    ORDER_TYPE: 'PO — Order type',
    PO_NUMBER: 'PO — PO number',
    RE_ENCUMBER: 'PO — Re-encumber',
    UPDATED_AT: 'PO — Updated at',
    UUID: 'PO — UUID',
    WORKFLOW_STATUS: 'PO — Workflow status',
  },
  CREATED_BY: {
    EMAIL: 'Created by — Email',
    LAST_NAME_FIRST_NAME: 'Created by — Last name, first name',
    USERNAME: 'Created by — Username',
  },
  UPDATED_BY: {
    EMAIL: 'Updated by — Email',
    LAST_NAME_FIRST_NAME: 'Updated by — Last name, first name',
    USERNAME: 'Updated by — Username',
  },
};
