export const USERS_WITH_MANUAL_BLOCKS_FIELDS = {
  USER: {
    ACTIVE: 'User — Active',
    ADDRESS_CITY: 'User — Address — City',
    ADDRESS_COUNTRY: 'User — Address — Country',
    ADDRESS_LINE_1: 'User — Address — Line 1',
    ADDRESS_LINE_2: 'User — Address — Line 2',
    ADDRESS_POSTAL_CODE: 'User — Address — Postal code',
    ADDRESS_PRIMARY_ADDRESS: 'User — Address — Primary address',
    ADDRESS_REGION: 'User — Address — Region',
    ADDRESS_TYPE: 'User — Address — Type',
    BARCODE: 'User — Barcode',
    CREATED_BY_USER_UUID: 'User — Created by user UUID',
    DATE_OF_BIRTH: 'User — Date of birth',
    DEPARTMENT_NAMES: 'User — Department names',
    DEPARTMENT_UUIDS: 'User — Department UUIDs',
    EMAIL: 'User — Email',
    ENROLLMENT_DATE: 'User — Enrollment date',
    EXPIRATION_DATE: 'User — Expiration date',
    EXTERNAL_SYSTEM_ID: 'User — External system ID',
    FIRST_NAME: 'User — First name',
    LAST_NAME: 'User — Last name',
    LAST_NAME_FIRST_NAME: 'User — Last name, first name',
    MIDDLE_NAME: 'User — Middle name',
    MOBILE_PHONE: 'User — Mobile phone',
    PHONE: 'User — Phone',
    PREFERRED_CONTACT_TYPE: 'User — Preferred contact type',
    PREFERRED_FIRST_NAME: 'User — Preferred first name',
    PRONOUNS: 'User — Pronouns',
    TAGS: 'User — Tags',
    TYPE: 'User — Type',
    UPDATED_BY_USER_UUID: 'User — Updated by user UUID',
    USER_CREATED_DATE: 'User — User created date',
    USER_UPDATED_DATE: 'User — User updated date',
    USER_UUID: 'User — User UUID',
    USERNAME: 'User — Username',
  },
  PATRON_GROUP: {
    NAME: 'User — Patron group — Name',
  },
  MANUAL_BLOCKS: {
    BORROWING: 'Manual blocks — Borrowing',
    CODE: 'Manual blocks — Code',
    CREATED_AT: 'Manual blocks — Created at',
    DESCRIPTION: 'Manual blocks — Description',
    EXPIRATION_DATE: 'Manual blocks — Expiration date',
    PATRON_MESSAGE: 'Manual blocks — Patron message',
    RENEWALS: 'Manual blocks — Renewals',
    REQUESTS: 'Manual blocks — Requests',
    STAFF_INFORMATION: 'Manual blocks — Staff information',
    UPDATED_AT: 'Manual blocks — Updated at',
    UUID: 'Manual blocks — UUID',
  },
  MANUAL_BLOCKS_CREATED_BY: {
    EMAIL: 'Manual blocks — Created by — Email',
    LAST_NAME_FIRST_NAME: 'Manual blocks — Created by — Last name, first name',
    USERNAME: 'Manual blocks — Created by — Username',
  },
  MANUAL_BLOCKS_UPDATED_BY: {
    EMAIL: 'Manual blocks — Updated by — Email',
    LAST_NAME_FIRST_NAME: 'Manual blocks — Updated by — Last name, first name',
    USERNAME: 'Manual blocks — Updated by — Username',
  },
};
