export const USERS_WITH_FEES_FINES_LOANS_FIELDS = {
  USER: {
    ACTIVE: 'User — Active',
    ADDRESS_CITY: 'User — Address — City',
    ADDRESS_COUNTRY: 'User — Address — Country',
    ADDRESS_LINE_1: 'User — Address — Line 1',
    ADDRESS_LINE_2: 'User — Address — Line 2',
    ADDRESS_POSTAL_CODE: 'User — Address — Postal code',
    ADDRESS_PRIMARY_ADDRESS: 'User — Address — Primary address',
    ADDRESS_REGION: 'User — Address — Region',
    ADDRESS_TYPE: 'User — Address — Type',
    BARCODE: 'User — Barcode',
    CREATED_BY_USER_UUID: 'User — Created by user UUID',
    DATE_OF_BIRTH: 'User — Date of birth',
    DEPARTMENT_NAMES: 'User — Department names',
    EMAIL: 'User — Email',
    ENROLLMENT_DATE: 'User — Enrollment date',
    EXPIRATION_DATE: 'User — Expiration date',
    EXTERNAL_SYSTEM_ID: 'User — External system ID',
    FIRST_NAME: 'User — First name',
    LAST_NAME: 'User — Last name',
    LAST_NAME_FIRST_NAME: 'User — Last name, first name',
    MIDDLE_NAME: 'User — Middle name',
    MOBILE_PHONE: 'User — Mobile phone',
    PHONE: 'User — Phone',
    PREFERRED_CONTACT_TYPE: 'User — Preferred contact type',
    PREFERRED_FIRST_NAME: 'User — Preferred first name',
    PRONOUNS: 'User — Pronouns',
    TAGS: 'User — Tags',
    TYPE: 'User — Type',
    UPDATED_BY_USER_UUID: 'User — Updated by user UUID',
    USER_CREATED_DATE: 'User — User created date',
    USER_UPDATED_DATE: 'User — User updated date',
    USER_UUID: 'User — User UUID',
    USERNAME: 'User — Username',
  },
  PATRON_GROUP: {
    NAME: 'User — Patron group — Name',
  },
  FEE_FINE_ACCOUNT: {
    AMOUNT: 'Fee/Fine account — Amount',
    BARCODE: 'Fee/Fine account — Barcode',
    CREATED_AT: 'Fee/Fine account — Created at',
    DUE_DATE: 'Fee/Fine account — Due date',
    FEE_FINE_OWNER: 'Fee/Fine account — Fee/fine owner',
    FEE_FINE_TYPE: 'Fee/Fine account — Fee/fine type',
    LOCATION: 'Fee/Fine account — Location',
    MATERIAL_TYPE: 'Fee/Fine account — Material type',
    PAYMENT_STATUS_NAME: 'Fee/Fine account — Payment status name',
    REMAINING: 'Fee/Fine account — Remaining',
    RETURNED_DATE: 'Fee/Fine account — Returned date',
    STATUS_NAME: 'Fee/Fine account — Status name',
    UPDATED_AT: 'Fee/Fine account — Updated at',
    USER_UUID: 'Fee/Fine account — User UUID',
    UUID: 'Fee/Fine account — UUID',
  },
  LOAN: {
    ACTION: 'Loan — Action',
    CHECKOUT_DATE: 'Loan — Checkout date',
    CLAIMED_RETURNED_DATE: 'Loan — Claimed returned date',
    CREATED_AT: 'Loan — Created at',
    CREATED_BY_USER_UUID: 'Loan — Created by user UUID',
    DECLARED_LOST_DATE: 'Loan — Declared lost date',
    DUE_DATE: 'Loan — Due date',
    DUE_DATE_CHANGED_BY_RECALL: 'Loan — Due date changed by recall',
    RENEWAL_COUNT: 'Loan — Renewal count',
    RETURN_DATE: 'Loan — Return date',
    STATUS_NAME: 'Loan — Status name',
    UPDATED_BY_USER_UUID: 'Loan — Updated by user UUID',
    UUID: 'Loan — UUID',
  },
  ITEM: {
    ACCESSION_NUMBER: 'Item — Accession number',
    ADMINISTRATIVE_NOTES: 'Item — Administrative notes',
    BARCODE: 'Item — Barcode',
    CHECK_IN_NOTES_NOTE: 'Item — Check in notes — Note',
    CHECK_IN_NOTES_STAFF_ONLY: 'Item — Check in notes — Staff only',
    CHECK_OUT_NOTES_NOTE: 'Item — Check out notes — Note',
    CHECK_OUT_NOTES_STAFF_ONLY: 'Item — Check out notes — Staff only',
    CHRONOLOGY: 'Item — Chronology',
    COPY_NUMBER: 'Item — Copy number',
    CREATED_DATE: 'Item — Created date',
    DESCRIPTION_OF_PIECES: 'Item — Description of pieces',
    DISPLAY_SUMMARY: 'Item — Display summary',
    EFFECTIVE_CALL_NUMBER: 'Item — Effective call number',
    EFFECTIVE_SHELVING_ORDER: 'Item — Effective shelving order',
    ELECTRONIC_ACCESS_LINK_TEXT: 'Item — Electronic access — Link text',
    ELECTRONIC_ACCESS_MATERIAL_SPECIFIED: 'Item — Electronic access — Material specified',
    ELECTRONIC_ACCESS_URI: 'Item — Electronic access — URI',
    ELECTRONIC_ACCESS_URL_PUBLIC_NOTE: 'Item — Electronic access — URL public note',
    ELECTRONIC_ACCESS_URL_RELATIONSHIP: 'Item — Electronic access — URL relationship',
    ENUMERATION: 'Item — Enumeration',
    FORMER_IDENTIFIERS: 'Item — Former identifiers',
    ITEM_ADDITIONAL_CALL_NUMBERS_CALL_NUMBER: 'Item — Item additional call numbers — Call number',
    ITEM_ADDITIONAL_CALL_NUMBERS_PREFIX: 'Item — Item additional call numbers — Prefix',
    ITEM_ADDITIONAL_CALL_NUMBERS_SUFFIX: 'Item — Item additional call numbers — Suffix',
    ITEM_ADDITIONAL_CALL_NUMBERS_TYPE: 'Item — Item additional call numbers — Type',
    ITEM_CALL_NUMBER: 'Item — Item call number',
    ITEM_CALL_NUMBER_PREFIX: 'Item — Item call number prefix',
    ITEM_CALL_NUMBER_SUFFIX: 'Item — Item call number suffix',
    ITEM_HRID: 'Item — Item HRID',
    ITEM_UUID: 'Item — Item UUID',
    LAST_CHECK_IN_DATE_TIME: 'Item — Last check in date time',
    NOTES_NOTE: 'Item — Notes — Note',
    NOTES_NOTE_TYPE: 'Item — Notes — Note type',
    NOTES_STAFF_ONLY: 'Item — Notes — Staff only',
    NUMBER_OF_MISSING_PIECES: 'Item — Number of missing pieces',
    NUMBER_OF_PIECES: 'Item — Number of pieces',
    PURCHASE_ORDER_LINE_IDENTIFIER: 'Item — Purchase order line identifier',
    SORT_ORDER: 'Item — Sort order',
    STATISTICAL_CODES: 'Item — Statistical codes',
    STATUS: 'Item — Status',
    STATUS_DATE: 'Item — Status date',
    SUPPRESS_FROM_DISCOVERY: 'Item — Suppress from discovery',
    TAGS: 'Item — Tags',
    UPDATED_DATE: 'Item — Updated date',
    VERSION: 'Item — Version',
    VOLUME: 'Item — Volume',
    YEAR_CAPTION: 'Item — Year, caption',
  },
};
