import { Button, createInteractor, perform } from '@bigtest/interactor';
import { isVisible } from 'element-is-visible';

function label(element) {
  return element.querySelector('[class^=labelArea]').textContent.trim();
}

export default createInteractor('accordion')({
  selector: '[class^=accordion]',
  locator: label,
  filters: {
    label,
    id: el => el.id,
    open: el => isVisible(el.querySelector('[class^=content]')),
    contentHeight: el => el.querySelector('[class^=content]').offsetHeight,
    contentId: el => {
      const id = el.querySelector('[class^=content]').id;
      if (id.startsWith('accordion')) {
        return '@@autogenerated@@';
      } else {
        return id;
      }
    },
    focused: el => {
      const focus = el.ownerDocument.activeElement;
      return el.contains(focus);
    },
    index: (el) => {
      const set = el.parentNode;
      const accordions = [...set.querySelectorAll('[class^=accordion]')];

      for (let i = 0; i < accordions.length; i++) {
        if (el === accordions[i]) {
          return i;
        }
      }

      return undefined;
    }
  },
  actions: {
    clickHeader: perform(el => el.querySelector('[class^=labelArea-]').click()),
    focus: interactor => interactor.find(Button()).focus()
  }
});
