import './acq-units';
import './auth';
import './circulation';
import './finance';
import './inventory';
import './tags';
import './users';
import './servicePoints';
import './requests';
import './proxy';
import './blocks';
import './owners';
import './fees-fines';
import './organizations';
import './permissions';
import './orders';
import './batch-groups';
import './data-import';
<<<<<<< HEAD
import './request-preference-storage';
=======
import './invoice';
import './instance';
>>>>>>> 40e342e830c9bb0e7684f70854c2130a97561ff0
