import Permissions from '../../../support/dictionary/permissions';
import HoldingsRecordView from '../../../support/fragments/inventory/holdingsRecordView';
import InventoryInstance from '../../../support/fragments/inventory/inventoryInstance';
import InventoryInstances from '../../../support/fragments/inventory/inventoryInstances';
import InventoryViewSource from '../../../support/fragments/inventory/inventoryViewSource';
import QuickMarcEditor from '../../../support/fragments/quickMarcEditor';
import TopMenu from '../../../support/fragments/topMenu';
import Users from '../../../support/fragments/users/users';
import getRandomPostfix, { randomNDigitNumber } from '../../../support/utils/stringTools';

describe('MARC', () => {
  describe('MARC Holdings', () => {
    const randomPostfix = getRandomPostfix();
    // Simulates the "old 001 becomes 035 $a" behavior of Data Import re-importing a holdings
    // record: a system will generate a brand-new 001 and stash the previous one into 035.
    const simulatedOldHoldingsId = `ho${randomNDigitNumber(9)}`;

    const testData = {
      bibTitle: `AT_C407738_MarcBibInstance_${randomPostfix}`,
      tags: {
        tagLDR: 'LDR',
        tag001: '001',
        tag002: '002',
        tag004: '004',
        tag005: '005',
        tag006: '006',
        tag007: '007',
        tag008: '008',
        tag009: '009',
        tag010: '010',
        tag020: '020',
        tag024: '024',
        tag035: '035',
        tag337: '337',
        tag541: '541',
        tag845: '845',
        tag852: '852',
        tag856: '856',
        tag999: '999',
      },
      fieldValues: {
        tag002: 'Value002',
        tag009: 'Value009',
        tag010: '$a Value010',
        tag020: '$a Value020',
        tag024: '$a Value024',
        tag035: `$a ${simulatedOldHoldingsId}`,
        tag337: '$a Value337',
        tag541: '$a Value541',
        tag845: '$a Value845',
        tag856: '$a Value856',
      },
    };
    // Freshly-created record: 001 and 005 are auto-generated by the API and land as LDR,001,005
    // up top (005 right after 001, NOT in its ascending-tag slot) - everything else follows in
    // the order supplied to createMarcHoldingsViaAPI, with 999 auto-appended at the end
    const initialFieldsOrder = [
      testData.tags.tagLDR,
      testData.tags.tag001,
      testData.tags.tag005,
      testData.tags.tag002,
      testData.tags.tag004,
      testData.tags.tag006,
      testData.tags.tag007,
      testData.tags.tag008,
      testData.tags.tag009,
      testData.tags.tag010,
      testData.tags.tag020,
      testData.tags.tag024,
      testData.tags.tag035,
      testData.tags.tag337,
      testData.tags.tag541,
      testData.tags.tag845,
      testData.tags.tag852,
      testData.tags.tag856,
      testData.tags.tag999,
    ];
    // Target order (top to bottom): LDR stays first, everything else is fully reversed
    const expectedOrder = [testData.tags.tagLDR, ...initialFieldsOrder.slice(1).reverse()];

    // Only LDR (row 0) is completely fixed. LDR/001/005 have neither "Add" nor "Delete" icons;
    // 004/008/852/999 additionally lack "Delete" only (they still have "Add") - both are purely
    // tag-based and independent of the field's current row.
    const noDeleteTags = [
      testData.tags.tagLDR,
      testData.tags.tag001,
      testData.tags.tag005,
      testData.tags.tag004,
      testData.tags.tag008,
      testData.tags.tag852,
      testData.tags.tag999,
    ];
    const noAddTags = [testData.tags.tagLDR, testData.tags.tag001, testData.tags.tag005];

    // Verifies move/add/delete icon visibility for every row of the given tag order, from the
    // very first check (this isn't a save-triggered change, LDR/001/005/etc. never have
    // add/delete icons regardless of when you look). Up/down visibility is purely position-based
    // (row 0 = LDR = none; row 1 = down-only; last row = up-only; everything between = both) -
    // add/delete visibility is tag-based and independent of where the tag currently sits.
    const verifyFieldIconsForOrder = (order) => {
      order.forEach((tag, row) => {
        if (row === 0) {
          QuickMarcEditor.verifyEditableFieldIcons(row, false, false, false, false);
          return;
        }
        const isArrowUpShown = row !== 1;
        const isArrowDownShown = row !== order.length - 1;
        QuickMarcEditor.verifyEditableFieldIcons(
          row,
          isArrowUpShown,
          isArrowDownShown,
          !noDeleteTags.includes(tag),
          !noAddTags.includes(tag),
        );
      });
    };

    const permissions = [
      Permissions.inventoryAll.gui,
      Permissions.uiQuickMarcQuickMarcHoldingsEditorAll.gui,
    ];

    let user;
    let instanceId;
    let location;

    before('Create test data', () => {
      cy.getAdminToken();
      cy.createTempUser(permissions).then((userProperties) => {
        user = userProperties;

        cy.getLocations({
          limit: 1,
          query: '(isActive=true and name<>"AT_*" and name<>"*auto*")',
        }).then((res) => {
          location = res;
        });

        cy.createSimpleMarcBibViaAPI(testData.bibTitle).then((id) => {
          instanceId = id;

          cy.getInstanceById(id).then((instanceData) => {
            cy.createMarcHoldingsViaAPI(instanceData.id, [
              { tag: testData.tags.tag002, content: testData.fieldValues.tag002 },
              { tag: testData.tags.tag004, content: instanceData.hrid },
              {
                tag: testData.tags.tag006,
                content: { Type: 'm', Audn: '\\', Form: '\\', File: '\\', GPub: '\\' },
              },
              {
                tag: testData.tags.tag007,
                content: {
                  Category: 'z',
                  SMD: '\\',
                },
                indicators: ['\\', '\\'],
              },
              { tag: testData.tags.tag008, content: QuickMarcEditor.defaultValid008HoldingsValues },
              { tag: testData.tags.tag009, content: testData.fieldValues.tag009 },
              {
                tag: testData.tags.tag010,
                content: testData.fieldValues.tag010,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag020,
                content: testData.fieldValues.tag020,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag024,
                content: testData.fieldValues.tag024,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag035,
                content: testData.fieldValues.tag035,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag337,
                content: testData.fieldValues.tag337,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag541,
                content: testData.fieldValues.tag541,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag845,
                content: testData.fieldValues.tag845,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag852,
                content: `$b ${location.code}`,
                indicators: ['\\', '\\'],
              },
              {
                tag: testData.tags.tag856,
                content: testData.fieldValues.tag856,
                indicators: ['\\', '\\'],
              },
            ]);
          });
        });

        cy.login(user.username, user.password, {
          path: TopMenu.inventoryPath,
          waiter: InventoryInstances.waitContentLoading,
        });
      });
    });

    after('Delete test data', () => {
      cy.getAdminToken();
      Users.deleteViaApi(user.userId);
      if (instanceId) InventoryInstances.deleteInstanceAndItsHoldingsAndItemsViaApi(instanceId);
    });

    it(
      'C407738 Verify that all fields (except "LDR") can be moved and saved when editing "MARC holdings" record (promin)',
      { tags: ['extendedPath', 'promin', 'C407738'] },
      () => {
        InventoryInstances.searchByTitle(instanceId);
        InventoryInstances.selectInstanceById(instanceId);
        InventoryInstance.waitLoading();
        InventoryInstance.waitInstanceRecordViewOpened();
        InventoryInstance.openHoldingView();

        // Step 1: Open "Edit MARC holdings" pane, verify initial fields/icons
        HoldingsRecordView.editInQuickMarc();
        QuickMarcEditor.waitLoading();
        QuickMarcEditor.verifyRowOrderByTags(initialFieldsOrder);
        verifyFieldIconsForOrder(initialFieldsOrder);

        // Step 2: Arrange fields into the fully-reversed target order (LDR stays first) using
        // the proven bulk "bubble the last unplaced field to the front" reversal trick
        for (let movesCount = initialFieldsOrder.length - 2; movesCount >= 1; movesCount--) {
          for (let i = 0; i < movesCount; i++) {
            QuickMarcEditor.moveFieldUp(initialFieldsOrder.length - 1 - i);
          }
        }
        QuickMarcEditor.verifyRowOrderByTags(expectedOrder);

        // Step 3: Save & keep editing - verify order persists and icon states swap accordingly
        QuickMarcEditor.clickSaveAndKeepEditingButton();
        QuickMarcEditor.checkAfterSaveAndKeepEditing();
        QuickMarcEditor.verifyRowOrderByTags(expectedOrder);
        verifyFieldIconsForOrder(expectedOrder);

        // Step 4: Close the editor, verify the same order in "View source" - closing quickMarc
        // for a holdings record returns to the Holdings record view, not instance details
        QuickMarcEditor.close();
        HoldingsRecordView.waitLoading();
        HoldingsRecordView.viewSource();
        InventoryViewSource.verifyFieldsOrder(expectedOrder);
      },
    );
  });
});
