export const INVOICE_LINE_VIEW_FIELDS = {
  DESCRIPTION: 'Description',
  PO_LINE_NUMBER: 'PO line number',
  STATUS: 'Status',
  SUB_TOTAL: 'Sub-total',
  TOTAL_EXCHANGED: 'Total (Exchanged)',
  QUANTITY: 'Quantity',
};

export const EXPORT_INVOICE_LINE_FIELDS = {
  ACCOUNT_NUMBER: 'Account number',
  COMMENT: 'Comment',
  DESCRIPTION: 'Description (Title)',
  DISBURSEMENT_DATE: 'Disbursement date',
  DISBURSEMENT_NUMBER: 'Disbursement number',
  EXTERNAL_ACCOUNT_NUMBER: 'External account number',
  INVOICE_LINE_CREATED_BY: 'Created by (Invoice Line)',
  INVOICE_LINE_DATE_CREATED: 'Created on (Invoice Line)',
  INVOICE_LINE_DATE_UPDATED: 'Updated on (Invoice Line)',
  INVOICE_LINE_NUMBER: 'Invoice line number',
  INVOICE_LINE_UPDATED_BY: 'Updated by (Invoice Line)',
  LINE_ACCOUNTING_CODE: 'Accounting code',
  LINE_ADJUSTMENTS: 'Invoice line adjustments',
  LINE_FUND_DISTRIBUTIONS: 'Invoice line fund distributions',
  LINE_SUB_TOTAL: 'Sub total',
  PO_LINE_NUMBER: 'POLine number',
  QUANTITY: 'Quantity',
  REFERENCE_NUMBERS: 'Vendor reference number, reference type',
  SUBSCRIPTION_END: 'Subscription end',
  SUBSCRIPTION_INFO: 'Subscription info',
  SUBSCRIPTION_START: 'Subscription start',
  TOTAL: 'Total',
  LINE_TAGS: 'Invoice line tags',
  VOUCHER_DATE: 'Voucher date',
  VOUCHER_NUMBER: 'Voucher number',
  VOUCHER_STATUS: 'Voucher status',
};
