import getRandomPostfix from '../../../../utils/stringTools';

export default {
  MARC_AUTHORITY: {
    name: 'marcAuthority',
    recordType: 'MARC_AUTHORITY',
    marcMappingOption: 'UPDATE',
    mappingFields: [
      {
        name: 'discoverySuppress',
        enabled: true,
        path: 'marcAuthority.discoverySuppress',
        value: null,
        booleanFieldAction: 'IGNORE',
        subfields: [],
      },
      {
        name: 'hrid',
        enabled: true,
        path: 'marcAuthority.hrid',
        value: '',
        subfields: [],
      },
    ],
  },
  ITEM: {
    name: 'item',
    recordType: 'ITEM',
    mappingFields: [
      {
        name: 'discoverySuppress',
        enabled: true,
        path: 'item.discoverySuppress',
        value: null,
        subfields: [],
      },
      { name: 'hrid', enabled: true, path: 'item.hrid', value: '', subfields: [] },
      { name: 'barcode', enabled: true, path: 'item.barcode', value: '', subfields: [] },
      {
        name: 'accessionNumber',
        enabled: true,
        path: 'item.accessionNumber',
        value: '',
        subfields: [],
      },
      {
        name: 'itemIdentifier',
        enabled: true,
        path: 'item.itemIdentifier',
        value: '',
        subfields: [],
      },
      { name: 'formerIds', enabled: true, path: 'item.formerIds[]', value: '', subfields: [] },
      {
        name: 'statisticalCodeIds',
        enabled: true,
        path: 'item.statisticalCodeIds[]',
        value: '',
        subfields: [],
      },
      {
        name: 'administrativeNotes',
        enabled: true,
        path: 'item.administrativeNotes[]',
        value: '',
        subfields: [],
      },
      {
        name: 'materialType.id',
        enabled: true,
        path: 'item.materialType.id',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      { name: 'copyNumber', enabled: true, path: 'item.copyNumber', value: '', subfields: [] },
      {
        name: 'itemLevelCallNumberTypeId',
        enabled: true,
        path: 'item.itemLevelCallNumberTypeId',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      {
        name: 'itemLevelCallNumberPrefix',
        enabled: true,
        path: 'item.itemLevelCallNumberPrefix',
        value: '',
        subfields: [],
      },
      {
        name: 'itemLevelCallNumber',
        enabled: true,
        path: 'item.itemLevelCallNumber',
        value: '',
        subfields: [],
      },
      {
        name: 'itemLevelCallNumberSuffix',
        enabled: true,
        path: 'item.itemLevelCallNumberSuffix',
        value: '',
        subfields: [],
      },
      {
        name: 'numberOfPieces',
        enabled: true,
        path: 'item.numberOfPieces',
        value: '',
        subfields: [],
      },
      {
        name: 'descriptionOfPieces',
        enabled: true,
        path: 'item.descriptionOfPieces',
        value: '',
        subfields: [],
      },
      { name: 'enumeration', enabled: true, path: 'item.enumeration', value: '', subfields: [] },
      { name: 'chronology', enabled: true, path: 'item.chronology', value: '', subfields: [] },
      { name: 'volume', enabled: true, path: 'item.volume', value: '', subfields: [] },
      {
        name: 'yearCaption',
        enabled: true,
        path: 'item.yearCaption[]',
        value: '',
        subfields: [],
      },
      {
        name: 'numberOfMissingPieces',
        enabled: true,
        path: 'item.numberOfMissingPieces',
        value: '',
        subfields: [],
      },
      {
        name: 'missingPieces',
        enabled: true,
        path: 'item.missingPieces',
        value: '',
        subfields: [],
      },
      {
        name: 'missingPiecesDate',
        enabled: true,
        path: 'item.missingPiecesDate',
        value: '',
        subfields: [],
      },
      {
        name: 'itemDamagedStatusId',
        enabled: true,
        path: 'item.itemDamagedStatusId',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      {
        name: 'itemDamagedStatusDate',
        enabled: true,
        path: 'item.itemDamagedStatusDate',
        value: '',
        subfields: [],
      },
      { name: 'notes', enabled: true, path: 'item.notes[]', value: '', subfields: [] },
      {
        name: 'permanentLoanType.id',
        enabled: true,
        path: 'item.permanentLoanType.id',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      {
        name: 'temporaryLoanType.id',
        enabled: true,
        path: 'item.temporaryLoanType.id',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      { name: 'status.name', enabled: true, path: 'item.status.name', value: '', subfields: [] },
      {
        name: 'circulationNotes',
        enabled: true,
        path: 'item.circulationNotes[]',
        value: '',
        subfields: [],
      },
      {
        name: 'permanentLocation.id',
        enabled: true,
        path: 'item.permanentLocation.id',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      {
        name: 'temporaryLocation.id',
        enabled: true,
        path: 'item.temporaryLocation.id',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      {
        name: 'electronicAccess',
        enabled: true,
        path: 'item.electronicAccess[]',
        value: '',
        subfields: [],
      },
    ],
  },
  HOLDINGS: {
    name: 'holdings',
    recordType: 'HOLDINGS',
    mappingFields: [
      {
        name: 'discoverySuppress',
        enabled: true,
        path: 'holdings.discoverySuppress',
        value: '',
        subfields: [],
      },
      {
        name: 'hrid',
        enabled: false,
        path: 'holdings.discoverySuppress',
        value: '',
        subfields: [],
      },
      {
        name: 'formerIds',
        enabled: true,
        path: 'holdings.formerIds[]',
        value: '',
        subfields: [],
      },
      {
        name: 'holdingsTypeId',
        enabled: true,
        path: 'holdings.holdingsTypeId',
        value: '',
        subfields: [],
      },
      {
        name: 'statisticalCodeIds',
        enabled: true,
        path: 'holdings.statisticalCodeIds[]',
        value: '',
        subfields: [],
      },
      {
        name: 'administrativeNotes',
        enabled: true,
        path: 'holdings.administrativeNotes[]',
        value: '',
        subfields: [],
      },
      {
        name: 'shelvingOrder',
        enabled: true,
        path: 'holdings.shelvingOrder',
        value: '',
        subfields: [],
      },
      {
        name: 'shelvingTitle',
        enabled: true,
        path: 'holdings.shelvingTitle',
        value: '',
        subfields: [],
      },
      {
        name: 'copyNumber',
        enabled: true,
        path: 'holdings.copyNumber',
        value: '',
        subfields: [],
      },
      {
        name: 'callNumberTypeId',
        enabled: true,
        path: 'holdings.callNumberTypeId',
        value: '',
        subfields: [],
      },
      {
        name: 'callNumberPrefix',
        enabled: true,
        path: 'holdings.callNumberPrefix',
        value: '',
        subfields: [],
      },
      {
        name: 'callNumber',
        enabled: true,
        path: 'holdings.callNumber',
        value: '',
        subfields: [],
      },
      {
        name: 'callNumberSuffix',
        enabled: true,
        path: 'holdings.callNumberSuffix',
        value: '',
        subfields: [],
      },
      {
        name: 'numberOfItems',
        enabled: true,
        path: 'holdings.numberOfItems',
        value: '',
        subfields: [],
      },
      {
        name: 'holdingsStatements',
        enabled: true,
        path: 'holdings.holdingsStatements[]',
        value: '',
        subfields: [],
      },
      {
        name: 'holdingsStatementsForSupplements',
        enabled: true,
        path: 'holdings.holdingsStatementsForSupplements[]',
        value: '',
        subfields: [],
      },
      {
        name: 'holdingsStatementsForIndexes',
        enabled: true,
        path: 'holdings.holdingsStatementsForIndexes[]',
        value: '',
        subfields: [],
      },
      {
        name: 'illPolicyId',
        enabled: true,
        path: 'holdings.illPolicyId',
        value: '',
        subfields: [],
      },
      {
        name: 'digitizationPolicy',
        enabled: true,
        path: 'holdings.digitizationPolicy',
        value: '',
        subfields: [],
      },
      {
        name: 'retentionPolicy',
        enabled: true,
        path: 'holdings.retentionPolicy',
        value: '',
        subfields: [],
      },
      {
        name: 'notes',
        enabled: true,
        path: 'holdings.notes[]',
        value: '',
        subfields: [],
      },
      {
        name: 'electronicAccess',
        enabled: true,
        path: 'holdings.electronicAccess[]',
        value: '',
        subfields: [],
      },
      {
        name: 'receivingHistory.entries',
        enabled: true,
        path: 'holdings.receivingHistory.entries[]',
        value: '',
        subfields: [],
      },
    ],
  },
  INVOICE: {
    name: 'invoice',
    recordType: 'INVOICE',
    mappingFields: [
      {
        name: 'batchGroupId',
        enabled: true,
        path: 'invoice.batchGroupId',
        subfields: [],
        value: '""',
      },
      {
        name: 'vendorId',
        enabled: true,
        path: 'invoice.vendorId',
        value: '""',
        subfields: [],
      },
      {
        name: 'invoiceDate',
        enabled: true,
        path: 'invoice.invoiceDate',
        value: '###TODAY###',
        subfields: [],
      },
      {
        name: 'status',
        enabled: true,
        path: 'invoice.status',
        value: '"Open"',
        subfields: [],
      },
      {
        name: 'paymentDue',
        enabled: true,
        path: 'invoice.paymentDue',
        value: '',
        subfields: [],
      },
      {
        name: 'paymentTerms',
        enabled: true,
        path: 'invoice.paymentTerms',
        value: '',
        subfields: [],
      },
      {
        name: 'approvalDate',
        enabled: false,
        path: 'invoice.approvalDate',
        value: '',
        subfields: [],
      },
      {
        name: 'approvedBy',
        enabled: false,
        path: 'invoice.approvedBy',
        value: '',
        subfields: [],
      },
      {
        name: 'acqUnitIds',
        enabled: true,
        path: 'invoice.acqUnitIds[]',
        repeatableFieldAction: 'EXTEND_EXISTING',
        value: '',
        subfields: [
          {
            order: 0,
            path: 'invoice.acqUnitIds[]',
            fields: [
              {
                name: 'acqUnitIds',
                enabled: true,
                path: 'invoice.acqUnitIds[]',
                value: '',
              },
            ],
          },
        ],
      },
      {
        name: 'billTo',
        enabled: true,
        path: 'invoice.billTo',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'billToAddress',
        enabled: false,
        path: 'invoice.billToAddress',
        value: '',
        subfields: [],
      },
      {
        name: 'subTotal',
        enabled: false,
        path: 'invoice.subTotal',
        value: '',
        subfields: [],
      },
      {
        name: 'adjustmentsTotal',
        enabled: false,
        path: 'invoice.adjustmentsTotal',
        value: '',
        subfields: [],
      },
      {
        name: 'total',
        enabled: false,
        path: 'invoice.total',
        value: '',
        subfields: [],
      },
      {
        name: 'lockTotal',
        enabled: true,
        path: 'invoice.lockTotal',
        value: '',
        subfields: [],
      },
      { name: 'note', enabled: true, path: 'invoice.note', value: '', subfields: [] },
      {
        name: 'adjustments',
        enabled: true,
        path: 'invoice.adjustments[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'vendorInvoiceNo',
        enabled: true,
        path: 'invoice.vendorInvoiceNo',
        subfields: [],
        value: '1234',
      },
      {
        name: 'accountingCode',
        enabled: true,
        path: 'invoice.accountingCode',
        value: '"ERP-557.9514681950425535"',
        subfields: [],
      },
      {
        name: 'folioInvoiceNo',
        enabled: false,
        path: 'invoice.folioInvoiceNo',
        value: '',
        subfields: [],
      },
      {
        name: 'paymentMethod',
        enabled: true,
        path: 'invoice.paymentMethod',
        value: '"Cash"',
        subfields: [],
      },
      {
        name: 'chkSubscriptionOverlap',
        enabled: true,
        path: 'invoice.chkSubscriptionOverlap',
        value: null,
        booleanFieldAction: 'ALL_FALSE',
        subfields: [],
      },
      {
        name: 'exportToAccounting',
        enabled: true,
        path: 'invoice.exportToAccounting',
        value: null,
        booleanFieldAction: 'ALL_FALSE',
        subfields: [],
      },
      {
        name: 'currency',
        enabled: true,
        path: 'invoice.currency',
        subfields: [],
        value: '"USD"',
      },
      {
        name: 'currentExchangeRate',
        enabled: false,
        path: 'invoice.currentExchangeRate',
        value: '',
        subfields: [],
      },
      {
        name: 'exchangeRate',
        enabled: true,
        path: 'invoice.exchangeRate',
        value: '',
        subfields: [],
      },
      {
        name: 'invoiceLines',
        enabled: true,
        path: 'invoice.invoiceLines[]',
        repeatableFieldAction: 'EXTEND_EXISTING',
        value: '',
        subfields: [
          {
            order: 0,
            path: 'invoice.invoiceLines[]',
            fields: [
              {
                name: 'description',
                enabled: true,
                path: 'invoice.invoiceLines[].description',
                value: 'description',
              },
              {
                name: 'poLineId',
                enabled: true,
                path: 'invoice.invoiceLines[].poLineId',
                value: '',
              },
              {
                name: 'invoiceLineNumber',
                enabled: false,
                path: 'invoice.invoiceLines[].invoiceLineNumber',
                value: '',
              },
              {
                name: 'invoiceLineStatus',
                enabled: false,
                path: 'invoice.invoiceLines[].invoiceLineStatus',
                value: '',
              },
              {
                name: 'referenceNumbers',
                enabled: true,
                path: 'invoice.invoiceLines[].referenceNumbers[]',
                repeatableFieldAction: null,
                value: '',
                subfields: [],
              },
              {
                name: 'subscriptionInfo',
                enabled: true,
                path: 'invoice.invoiceLines[].subscriptionInfo',
                value: '',
              },
              {
                name: 'subscriptionStart',
                enabled: true,
                path: 'invoice.invoiceLines[].subscriptionStart',
                value: '',
              },
              {
                name: 'subscriptionEnd',
                enabled: true,
                path: 'invoice.invoiceLines[].subscriptionEnd',
                value: '',
              },
              {
                name: 'comment',
                enabled: true,
                path: 'invoice.invoiceLines[].comment',
                value: '',
              },
              {
                name: 'lineAccountingCode',
                enabled: false,
                path: 'invoice.invoiceLines[].accountingCode',
                value: '',
              },
              {
                name: 'accountNumber',
                enabled: true,
                path: 'invoice.invoiceLines[].accountNumber',
              },
              {
                name: 'quantity',
                enabled: true,
                path: 'invoice.invoiceLines[].quantity',
                value: '1',
              },
              {
                name: 'lineSubTotal',
                enabled: true,
                path: 'invoice.invoiceLines[].subTotal',
                value: '10',
              },
              {
                name: 'releaseEncumbrance',
                enabled: true,
                path: 'invoice.invoiceLines[].releaseEncumbrance',
                value: null,
                booleanFieldAction: 'ALL_FALSE',
              },
              {
                name: 'fundDistributions',
                enabled: true,
                path: 'invoice.invoiceLines[].fundDistributions[]',
                repeatableFieldAction: null,
                value: '',
                subfields: [],
              },
              {
                name: 'lineAdjustments',
                enabled: true,
                path: 'invoice.invoiceLines[].adjustments[]',
                repeatableFieldAction: null,
                value: '',
                subfields: [],
              },
            ],
          },
        ],
      },
    ],
  },
  ORDER: {
    name: 'order',
    recordType: 'ORDER',
    mappingFields: [
      {
        name: 'workflowStatus',
        enabled: true,
        path: 'order.po.workflowStatus',
        value: '"Pending"',
        subfields: [],
      },
      {
        name: 'approved',
        enabled: true,
        path: 'order.po.approved',
        value: null,
        booleanFieldAction: 'ALL_FALSE',
        subfields: [],
      },
      {
        name: 'poLinesLimit',
        enabled: false,
        path: 'order.po.poLinesLimit',
        value: '"1"',
        subfields: [],
      },
      {
        name: 'overridePoLinesLimit',
        enabled: true,
        path: 'order.po.overridePoLinesLimit',
        value: '',
        subfields: [],
      },
      {
        name: 'prefix',
        enabled: true,
        path: 'order.po.poNumberPrefix',
        value: '',
        subfields: [],
      },
      {
        name: 'poNumber',
        enabled: true,
        path: 'order.po.poNumber',
        value: '',
        subfields: [],
      },
      {
        name: 'suffix',
        enabled: true,
        path: 'order.po.poNumberSuffix',
        value: '',
        subfields: [],
      },
      {
        name: 'vendor',
        enabled: true,
        path: 'order.po.vendor',
        value: '"f04651ab-a709-4c47-a4fd-4cf2650d000b"',
        subfields: [],
      },
      {
        name: 'orderType',
        enabled: true,
        path: 'order.po.orderType',
        value: '"One-Time"',
        subfields: [],
      },
      {
        name: 'acqUnitIds',
        enabled: true,
        path: 'order.po.acqUnitIds[]',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'assignedTo',
        enabled: true,
        path: 'order.po.assignedTo',
        value: '',
        subfields: [],
      },
      {
        name: 'billTo',
        enabled: true,
        path: 'order.po.billTo',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'shipTo',
        enabled: true,
        path: 'order.po.shipTo',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'manualPo',
        enabled: true,
        path: 'order.po.manualPo',
        value: null,
        booleanFieldAction: 'ALL_FALSE',
        subfields: [],
      },
      {
        name: 'reEncumber',
        enabled: true,
        path: 'order.po.reEncumber',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'notes',
        enabled: true,
        path: 'order.po.notes[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'title',
        enabled: true,
        path: 'order.poLine.titleOrPackage',
        subfields: [],
        value: `"autotest_po_line_${getRandomPostfix()}"`,
      },
      {
        name: 'receivingNote',
        enabled: true,
        path: 'order.poLine.details.receivingNote',
        value: '',
        subfields: [],
      },
      {
        name: 'isAcknowledged',
        enabled: true,
        path: 'order.poLine.details.isAcknowledged',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'subscriptionFrom',
        enabled: true,
        path: 'order.poLine.details.subscriptionFrom',
        value: '',
        subfields: [],
      },
      {
        name: 'subscriptionTo',
        enabled: true,
        path: 'order.poLine.details.subscriptionTo',
        value: '',
        subfields: [],
      },
      {
        name: 'subscriptionInterval',
        enabled: true,
        path: 'order.poLine.details.subscriptionInterval',
        value: '',
        subfields: [],
      },
      {
        name: 'publicationDate',
        enabled: true,
        path: 'order.poLine.publicationDate',
        value: '',
        subfields: [],
      },
      {
        name: 'publisher',
        enabled: true,
        path: 'order.poLine.publisher',
        value: '',
        subfields: [],
      },
      {
        name: 'edition',
        enabled: true,
        path: 'order.poLine.edition',
        value: '',
        subfields: [],
      },
      {
        name: 'contributors',
        enabled: true,
        path: 'order.poLine.contributors[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'productIds',
        enabled: true,
        path: 'order.poLine.details.productIds[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'description',
        enabled: true,
        path: 'order.poLine.description',
        value: '',
        subfields: [],
      },
      {
        name: 'poLineNumber',
        enabled: false,
        path: 'order.poLine.poLineNumber',
        value: '',
        subfields: [],
      },
      {
        name: 'acquisitionMethod',
        enabled: true,
        path: 'order.poLine.acquisitionMethod',
        value: '"Other"',
        acceptedValues: {
          '796596c4-62b5-4b64-a2ce-524c747afaa2': 'Approval Plan',
          '041035ad-b2a4-4aa0-b6a5-234b88bf938c': 'Demand Driven Acquisitions (DDA)',
          'd2420b93-7b93-41b7-8b42-798f64cb6dd2': 'Depository',
          'aaa541f3-39d2-4887-ab8f-6ba12d08ca52': 'Evidence Based Acquisitions (EBA)',
          '8a33895e-2c69-4a98-ab48-b7ec1fa852d0': 'Exchange',
          '86d12634-b848-4968-adf0-5a95ce41c41b': 'Free',
          '0a4163a5-d225-4007-ad90-2fb41b73efab': 'Gift',
          '0c9b09c9-b94f-4702-aa63-a7f43617a225': 'Internal transfer',
          '5771a8a4-9323-49ee-9002-1b068d71ff42': 'Membership',
          'da6703b1-81fe-44af-927a-94f24d1ab8ee': 'Other',
          'df26d81b-9d63-4ff8-bf41-49bf75cfa70e': 'Purchase',
          '306489dd-0053-49ee-a068-c316444a8f55': 'Purchase At Vendor System',
          'd0d3811c-19f8-4c57-a462-958165cdbbea': 'Technical',
        },
        subfields: [],
      },
      {
        name: 'automaticExport',
        enabled: true,
        path: 'order.poLine.automaticExport',
        value: null,
        booleanFieldAction: 'ALL_FALSE',
        subfields: [],
      },
      {
        name: 'orderFormat',
        enabled: true,
        path: 'order.poLine.orderFormat',
        value: '"Other"',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'receiptDate',
        enabled: true,
        path: 'order.poLine.receiptDate',
        value: '',
        subfields: [],
      },
      {
        name: 'receiptStatus',
        enabled: true,
        path: 'order.poLine.receiptStatus',
        value: '',
        subfields: [],
      },
      {
        name: 'paymentStatus',
        enabled: true,
        path: 'order.poLine.paymentStatus',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'source',
        enabled: false,
        path: 'order.poLine.source',
        value: '"MARC"',
        subfields: [],
      },
      {
        name: 'donor',
        enabled: true,
        path: 'order.poLine.donor',
        value: '',
        subfields: [],
      },
      {
        name: 'selector',
        enabled: true,
        path: 'order.poLine.selector',
        value: '',
        subfields: [],
      },
      {
        name: 'requester',
        enabled: true,
        path: 'order.poLine.requester',
        value: '',
        subfields: [],
      },
      {
        name: 'cancellationRestriction',
        enabled: true,
        path: 'order.poLine.cancellationRestriction',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'rush',
        enabled: true,
        path: 'order.poLine.rush',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'checkinItems',
        enabled: true,
        path: 'order.poLine.checkinItems',
        acceptedValues: {},
        subfields: [],
        value: '"false"',
      },
      {
        name: 'cancellationRestrictionNote',
        enabled: true,
        path: 'order.poLine.cancellationRestrictionNote',
        value: '',
        subfields: [],
      },
      {
        name: 'poLineDescription',
        enabled: true,
        path: 'order.poLine.poLineDescription',
        value: '',
        subfields: [],
      },
      {
        name: 'vendorDetail',
        enabled: true,
        path: 'order.poLine.vendorDetail.referenceNumbers[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'vendorAccount',
        enabled: true,
        path: 'order.poLine.vendorDetail.vendorAccount',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'instructions',
        enabled: true,
        path: 'order.poLine.vendorDetail.instructions',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'listUnitPrice',
        enabled: true,
        path: 'order.poLine.cost.listUnitPrice',
        value: '',
        subfields: [],
      },
      {
        name: 'quantityPhysical',
        enabled: true,
        path: 'order.poLine.cost.quantityPhysical',
        value: '',
        subfields: [],
      },
      {
        name: 'additionalCost',
        enabled: true,
        path: 'order.poLine.cost.additionalCost',
        value: '',
        subfields: [],
      },
      {
        name: 'currency',
        enabled: true,
        path: 'order.poLine.cost.currency',
        value: '"USD"',
        subfields: [],
      },
      {
        name: 'exchangeRate',
        enabled: true,
        path: 'order.poLine.cost.exchangeRate',
        value: '',
        subfields: [],
      },
      {
        name: 'electronicUnitPrice',
        enabled: true,
        path: 'order.poLine.cost.listUnitPriceElectronic',
        subfields: [],
      },
      {
        name: 'quantityElectronic',
        enabled: true,
        path: 'order.poLine.cost.quantityElectronic',
        subfields: [],
      },
      {
        name: 'discount',
        enabled: true,
        path: 'order.poLine.cost.discount',
        value: '',
        subfields: [],
      },
      {
        name: 'discountType',
        enabled: true,
        path: 'order.poLine.cost.discountType',
        value: 'percentage',
        subfields: [],
      },
      {
        name: 'fundDistribution',
        enabled: true,
        path: 'order.poLine.fundDistribution[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'locations',
        enabled: true,
        path: 'order.poLine.locations[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'materialSupplier',
        enabled: true,
        path: 'order.poLine.physical.materialSupplier',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'receiptDue',
        enabled: true,
        path: 'order.poLine.physical.receiptDue',
        value: '',
        subfields: [],
      },
      {
        name: 'expectedReceiptDate',
        enabled: true,
        path: 'order.poLine.physical.expectedReceiptDate',
        value: '',
        subfields: [],
      },
      {
        name: 'createInventory',
        enabled: true,
        path: 'order.poLine.physical.createInventory',
        value: '',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'materialType',
        enabled: true,
        path: 'order.poLine.physical.materialType',
        value: '',
        subfields: [],
        acceptedValues: {},
      },
      {
        name: 'volumes',
        enabled: true,
        path: 'order.poLine.physical.volumes[]',
        repeatableFieldAction: null,
        value: '',
        subfields: [],
      },
      {
        name: 'accessProvider',
        enabled: true,
        path: 'order.poLine.eresource.accessProvider',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'activationStatus',
        enabled: true,
        path: 'order.poLine.eresource.activated',
        value: null,
        booleanFieldAction: 'ALL_FALSE',
        subfields: [],
      },
      {
        name: 'activationDue',
        enabled: true,
        path: 'order.poLine.eresource.activationDue',
        subfields: [],
      },
      {
        name: 'createInventory',
        enabled: true,
        path: 'order.poLine.eresource.createInventory',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'materialType',
        enabled: true,
        path: 'order.poLine.eresource.materialType',
        acceptedValues: {},
        subfields: [],
      },
      {
        name: 'trial',
        enabled: true,
        path: 'order.poLine.eresource.trial',
        value: null,
        booleanFieldAction: 'ALL_FALSE',
        subfields: [],
      },
      {
        name: 'expectedActivation',
        enabled: true,
        path: 'order.poLine.eresource.expectedActivation',
        subfields: [],
      },
      {
        name: 'userLimit',
        enabled: true,
        path: 'order.poLine.eresource.userLimit',
        subfields: [],
      },
      {
        name: 'resourceUrl',
        enabled: true,
        path: 'order.poLine.eresource.resourceUrl',
        subfields: [],
      },
    ],
  },
};
