/* eslint-disable no-console */
const { parseGrep, shouldTestRun } = require('@cypress/grep/src/utils');
const globby = require('globby');
const fs = require('fs');
const { getTestNames } = require('find-test-names');
const { argv } = require('node:process');

let numberOfThreads = 1;
let grepTags = '';
let envVars = '';
const TESTS_EXECUTION_TIME_FILE = './doc/testsExecutionTime.json'; // file with tests execution times, generated by time-balancer.js script. Has format { "C1234": 120000, "C5678": 300000, ... }

// print process.argv
argv.forEach((val, index) => {
  console.log(`${index}: ${val}`);
  if (val.includes('tags=')) {
    grepTags = val.replace('tags=', '');
  }
  if (val.includes('threads=')) {
    numberOfThreads = Number(val.replace('threads=', ''));
  }
  if (val.includes('env=')) {
    envVars = val.replace('env=', '');
  }
});

if (grepTags === '') {
  throw new Error('No tags provided. Use tags=<tag1 tag2 ...> to specify tags to run.');
}

console.log(`\nNumber of threads: ${numberOfThreads}`);
console.log(`Environment variables: ${envVars}`);
console.log(`Tags: ${grepTags}\n`);

const parsedGrep = parseGrep(null, grepTags);

const specFiles = globby.sync('cypress/e2e/**/*.cy.js');
const testSpecsIds = [];
const chunks = Array.from({ length: numberOfThreads }, (_) => ({ totalDuration: 0, testIds: [] }));
specFiles.forEach((specFile) => {
  const testsInSpecFile = [];
  const text = fs.readFileSync(specFile, { encoding: 'utf8' });
  const testInfo = getTestNames(text);
  testInfo.tests.forEach((info) => {
    const shouldRun = shouldTestRun(parsedGrep, null, info.tags);
    if (shouldRun) {
      const filteredTags = info.tags.filter((tag) => tag.startsWith('C') || tag.startsWith('TC'));
      if (filteredTags.includes(undefined)) {
        console.log(`Test without ID found in file ${specFile} - ${info.tags}`);
      }
      testsInSpecFile.push(filteredTags[0]);
    }
  });
  if (testsInSpecFile.length > 0) {
    testSpecsIds.push(Array.from(new Set(testsInSpecFile)));
  }
});

if (testSpecsIds.length === 0) {
  throw new Error('No tests found with provided tags.');
}

console.log('Matched test IDs: ', testSpecsIds);

let testsExecutionTimes = {};
try {
  const testsExecutionTimeContent = fs.readFileSync(TESTS_EXECUTION_TIME_FILE, {
    encoding: 'utf8',
  });
  testsExecutionTimes = JSON.parse(testsExecutionTimeContent);
} catch (err) {
  console.error(`Error reading ${TESTS_EXECUTION_TIME_FILE} file.`, err);
}


function getTestDuration(testId) {
  if (testId in testsExecutionTimes) {
    return testsExecutionTimes[testId];
  } else {
    return 2 * 60 * 1000; // fallback duration for unknown test (2 minutes)
  }
}

function getTestDurationForSpec(testSpecId) {
  let duration = 0;
  testSpecId.forEach((testId) => {
    duration += getTestDuration(testId);
  });
  return duration;
}

for (const testSpecId of testSpecsIds) {
  chunks.sort((a, b) => a.totalDuration - b.totalDuration);
  chunks[0].testIds.push(...testSpecId);
  chunks[0].totalDuration += getTestDurationForSpec(testSpecId);
}

const fileJson = {};
fileJson.workers = [];

console.log(`\nNumber of chunks: ${chunks.length}\n`);
chunks.forEach((chunk, index) => {
  const parsedChunk = `--env ${envVars ? envVars + ',' : ''}grepTags='${chunk.testIds.join(' ')}'`;
  fileJson.workers.push(parsedChunk);
  console.log(
    `Chunk #${index + 1}: `,
    chunk.testIds.length,
    `, Estimated duration: ${new Date(chunk.totalDuration).toISOString().slice(11, 19)}`,
  );
  console.log(parsedChunk + '\n');
});

fs.writeFile('parallelWorkers.json', JSON.stringify(fileJson), 'utf8', (err) => {
  if (err) {
    console.error('Error writing file', err);
  } else {
    console.log('File has been written');
  }
});
