export default {
  hotKeys: {
    create: '{alt}N',
    edit: '{ctrl}{alt}E',
    save: '{ctrl}S',
    duplicate: '{alt}C',
    expandAllAccordions: '{ctrl}{alt}B',
    collapseAllAccordions: '{ctrl}{alt}G',
    expandOrCollapse: '{backspace}',
    goToSearchFilterPane: '{ctrl}{alt}H',
    openShortcutsModal: '{ctrl}{alt}K',
    close: '{esc}',
    copy: '{ctrl}C',
    paste: '{ctrl}V',
    find: '{ctrl}F',
    moveToPreviousSubfield: '{ctrl}[',
    moveToNextSubfield: '{ctrl}]',
    editMarc: '{ctrl}{shift}E',
  },
};
